################################################################################
# Author: Miguel Castilho Oliveira
# Date: March 31st 2021
# Description This program will convert letters into phone numbers
################################################################################
def convert_number(stringInput):
    #Doing what feels illegal but isnt :P
    a = stringInput.replace("a", "2")
    a = a.replace("b", "2")
    a = a.replace("c", "2")
    a = a.replace("d", "3")
    a = a.replace("e", "3")
    a = a.replace("f", "3")
    a = a.replace("g", "4")
    a = a.replace("h", "4")
    a = a.replace("i", "4")
    a = a.replace("j", "5")
    a = a.replace("k", "5")
    a = a.replace("l", "5")
    a = a.replace("m", "6")
    a = a.replace("n", "6")
    a = a.replace("o", "6")
    a = a.replace("p", "7")
    a = a.replace("q", "7")
    a = a.replace("r", "7")
    a = a.replace("s", "7")
    a = a.replace("t", "8")
    a = a.replace("u", "8")
    a = a.replace("v", "8")
    a = a.replace("w", "9")
    a = a.replace("x", "9")
    a = a.replace("y", "9")
    a = a.replace("z", "9")
    a = a.replace("A", "2")
    a = a.replace("B", "2")
    a = a.replace("C", "2")
    a = a.replace("D", "3")
    a = a.replace("E", "3")
    a = a.replace("F", "3")
    a = a.replace("G", "4")
    a = a.replace("H", "4")
    a = a.replace("I", "4")
    a = a.replace("J", "5")
    a = a.replace("K", "5")
    a = a.replace("L", "5")
    a = a.replace("M", "6")
    a = a.replace("N", "6")
    a = a.replace("O", "6")
    a = a.replace("P", "7")
    a = a.replace("Q", "7")
    a = a.replace("R", "7")
    a = a.replace("S", "7")
    a = a.replace("T", "8")
    a = a.replace("U", "8")
    a = a.replace("V", "8")
    a = a.replace("W", "9")
    a = a.replace("X", "9")
    a = a.replace("Y", "9")
    a = a.replace("Z", "9")
    return(a)
#Calling main function
def main():
    string = input("Enter a telephone number: ")
    realString = convert_number(string)
    print("The phone number is " + realString)
if __name__ == '__main__':
    main()